# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-22 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ground_location', models.CharField(max_length=50)),
                ('umpire_1', models.CharField(max_length=50)),
                ('umpire_2', models.CharField(max_length=50)),
                ('weather', models.CharField(choices=[('choice1', 'Sunny'), ('choice1', 'Sunny'), ('choice1', 'Sunny'), ('choice1', 'Sunny')], default='choice1', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, max_length=50)),
                ('home_ground', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='away_team', to='searching.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='home_team', to='searching.Team'),
        ),
    ]
