# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-28 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0003_auto_20170122_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_played', models.PositiveIntegerField()),
                ('batting_total_runs_scored', models.PositiveIntegerField()),
                ('batting_inning', models.PositiveIntegerField()),
                ('batting_high_score', models.PositiveIntegerField()),
                ('batting_average', models.FloatField()),
                ('batting_strike_rate', models.FloatField()),
                ('batting_50s', models.PositiveIntegerField()),
                ('batting_100s', models.PositiveIntegerField()),
                ('bowling_total_balls_faced', models.PositiveIntegerField()),
                ('bowling_runs_conceded', models.PositiveIntegerField()),
                ('bowling_wickets', models.PositiveIntegerField()),
                ('bowling_best_figures', models.CharField(max_length=10)),
                ('bowling_average', models.FloatField()),
                ('bowling_strike_rate', models.FloatField()),
                ('bowling_economy', models.FloatField()),
                ('bowling_5ws', models.PositiveIntegerField()),
                ('current_team_name', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='searching.Team')),
            ],
        ),
    ]
