# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-28 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0006_auto_20170128_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='bowling_best_figures',
            field=models.CharField(default='NA', max_length=10),
        ),
    ]
