# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-23 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0007_auto_20170128_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='batting_first',
            field=models.CharField(choices=[('home', 'home'), ('away', 'away')], default='home', max_length=50),
        ),
        migrations.AlterField(
            model_name='match',
            name='ground_location',
            field=models.CharField(choices=[('home', 'home'), ('away', 'away')], default='home', max_length=50),
        ),
    ]
