# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-14 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0010_match_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='result',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='match',
            name='umpire_1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='match',
            name='umpire_2',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
