# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-14 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0012_auto_20170314_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='result',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
