# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-24 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0016_matchteamplayer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='weather',
            field=models.CharField(choices=[('1', 'sunny'), ('2', 'sunny spells'), ('3', 'windy'), ('4', 'showers'), ('5', 'heavy rain'), ('6', 'rain and sun'), ('7', 'cloudy'), ('8', 'overcast'), ('9', 'other')], default='0', max_length=30),
        ),
    ]
