# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-21 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_squashed_0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballbyball',
            name='bowler',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ballbyball',
            name='extras',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ballbyball',
            name='extras_type',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ballbyball',
            name='how_out',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ballbyball',
            name='offstrike',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ballbyball',
            name='onstrike',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ballbyball',
            name='over',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ballbyball',
            name='people_involved',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ballbyball',
            name='runs',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ballbyball',
            name='total_runs',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ballbyball',
            name='total_wickets',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
