# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-24 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0002_auto_20170321_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballbyball',
            name='innings',
            field=models.IntegerField(default=1),
        ),
    ]
